[package]
name = "RustLoader"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
async-process = "2.3.0"
inquire = "0.7.1"
crossterm = "0.28.1"
reqwest = { version = "0.12.12", features = ["blocking"] }
